# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\graduation\workstation\fuxian_OCR\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1390, 850)
        MainWindow.setMinimumSize(QtCore.QSize(1390, 850))
        MainWindow.setMaximumSize(QtCore.QSize(1390, 850))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.open_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_button.setGeometry(QtCore.QRect(150, 620, 91, 41))
        self.open_button.setObjectName("open_button")
        self.run_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_button.setGeometry(QtCore.QRect(430, 620, 91, 41))
        self.run_button.setObjectName("run_button")
        self.text_button = QtWidgets.QPushButton(self.centralwidget)
        self.text_button.setGeometry(QtCore.QRect(820, 620, 111, 41))
        self.text_button.setObjectName("text_button")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 631, 521))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.left = QtWidgets.QLabel(self.groupBox)
        self.left.setText("")
        self.left.setObjectName("left")
        self.verticalLayout.addWidget(self.left)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(710, 30, 661, 521))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.right = QtWidgets.QLabel(self.groupBox_2)
        self.right.setText("")
        self.right.setObjectName("right")
        self.verticalLayout_2.addWidget(self.right)
        self.transfer = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.transfer.setGeometry(QtCore.QRect(660, 300, 41, 51))
        self.transfer.setText("")
        self.transfer.setObjectName("transfer")
        self.translate_button = QtWidgets.QPushButton(self.centralwidget)
        self.translate_button.setGeometry(QtCore.QRect(1110, 620, 91, 41))
        self.translate_button.setObjectName("translate_button")
        self.state_display = QtWidgets.QLabel(self.centralwidget)
        self.state_display.setGeometry(QtCore.QRect(260, 720, 811, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.state_display.setFont(font)
        self.state_display.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.state_display.setTextFormat(QtCore.Qt.PlainText)
        self.state_display.setAlignment(QtCore.Qt.AlignCenter)
        self.state_display.setWordWrap(False)
        self.state_display.setOpenExternalLinks(False)
        self.state_display.setObjectName("state_display")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1390, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.open = QtWidgets.QAction(MainWindow)
        self.open.setObjectName("open")
        self.save = QtWidgets.QAction(MainWindow)
        self.save.setObjectName("save")
        self.save_as = QtWidgets.QAction(MainWindow)
        self.save_as.setObjectName("save_as")
        self.exit = QtWidgets.QAction(MainWindow)
        self.exit.setObjectName("exit")
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setObjectName("about")
        self.man = QtWidgets.QAction(MainWindow)
        self.man.setObjectName("man")
        self.openCamera = QtWidgets.QAction(MainWindow)
        self.openCamera.setObjectName("openCamera")
        self.Run = QtWidgets.QAction(MainWindow)
        self.Run.setObjectName("Run")
        self.searchGood = QtWidgets.QAction(MainWindow)
        self.searchGood.setObjectName("searchGood")
        self.trans = QtWidgets.QAction(MainWindow)
        self.trans.setObjectName("trans")
        self.shoot = QtWidgets.QAction(MainWindow)
        self.shoot.setObjectName("shoot")
        self.menu.addAction(self.open)
        self.menu.addAction(self.shoot)
        self.menu.addAction(self.save)
        self.menu.addAction(self.save_as)
        self.menu.addSeparator()
        self.menu.addAction(self.exit)
        self.menu_2.addAction(self.about)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.man)
        self.menu_3.addAction(self.openCamera)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.Run)
        self.menu_3.addAction(self.searchGood)
        self.menu_3.addAction(self.trans)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scene Text Detection [author@suyame]"))
        self.open_button.setText(_translate("MainWindow", "打开摄像头"))
        self.run_button.setText(_translate("MainWindow", "运行"))
        self.text_button.setText(_translate("MainWindow", "提取关键词"))
        self.groupBox.setTitle(_translate("MainWindow", "原始图像"))
        self.groupBox_2.setTitle(_translate("MainWindow", "效果图像"))
        self.translate_button.setText(_translate("MainWindow", "搜索商品"))
        self.state_display.setText(_translate("MainWindow", "www.suyame.ltd"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.menu_3.setTitle(_translate("MainWindow", "功能"))
        self.open.setText(_translate("MainWindow", "打开"))
        self.open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.save.setText(_translate("MainWindow", "保存"))
        self.save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.save_as.setText(_translate("MainWindow", "另存为"))
        self.save_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.exit.setText(_translate("MainWindow", "退出"))
        self.exit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.about.setText(_translate("MainWindow", "关于"))
        self.man.setText(_translate("MainWindow", "使用手册"))
        self.openCamera.setText(_translate("MainWindow", "打开摄像头"))
        self.openCamera.setShortcut(_translate("MainWindow", "Ctrl+Shift+O"))
        self.Run.setText(_translate("MainWindow", "运行"))
        self.Run.setShortcut(_translate("MainWindow", "F5"))
        self.searchGood.setText(_translate("MainWindow", "提取关键词"))
        self.searchGood.setShortcut(_translate("MainWindow", "F10"))
        self.trans.setText(_translate("MainWindow", "查询商品"))
        self.trans.setShortcut(_translate("MainWindow", "F12"))
        self.shoot.setText(_translate("MainWindow", "拍照"))
        self.shoot.setShortcut(_translate("MainWindow", "Ctrl+F"))

